title: John D. Martin III
subtitle: Information Scientist / Digital Humanist
author: John D. Martin III
simple_search: http://google.com/search
description: "PhD student in the School of Information and Library Science at University of North Carolina at Chapel Hill."

email: me@johndmart.in
baseurl: ""
url: "http://johndmart.in"
twitterusername: jdmar3
githubusername: jdmar3
pgp: "67BB C847 14E0 C31A 736A 5E08 C787 DF8D D41F A8D1"
pgp-url: "http://johndmart.in/jdmar3.asc"
name: jdmar3

markdown: kramdown
kramdown:
  extensions: ["autolink"]
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
permalink: pretty
timezone: America/New_York
excerpt_separator: <!--more-->  # you can specify your own separator, of course.
exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md']
post:
  template: _post.txt
  extension: md
page:
  template: _page.txt
  extension: md
editor: gvim
git:
  branch: master
transfer:
  command: rsync
  settings: -av
  source: _site/
  destination: ~/workspace/jdmar3.github.io