title: John D. Martin III
subtitle: Information Scientist / Research Methodologist
author: John D. Martin III
simple_search: http://google.com/search
description: "PhD student in the School of Information and Library Science at University of North Carolina at Chapel Hill."

baseurl: ""
url: "https://johndmart.in"
enforce-ssl: "johndmart.in"
onion: "http://evpoyeb3anapeyrt.onion"

name: jdmar3

badge: face.jpg # this file should be located under /assets/img/

google_analytics: UA-91043800-1 # https://desiredpersona.com/google-analytics-jekyll/

#markdown: kramdown
#kramdown:

license: 'All content licensed under a <a target="_blank" rel="license" href="https://creativecommons.org/licenses/by-nc-nd/4.0/">Creative Commons Attribution-NonCommercial-NoDerivatives 4.0 International License</a>.'

license-img: '<a href="http://creativecommons.org/licenses/by-nc-nd/4.0/?ref=chooser-v1" target="_blank" rel="license noopener noreferrer" style="display:inline-block;"><img style="height:15px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/cc.svg?ref=chooser-v1 alt="CC ""><img style="height:15px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/by.svg?ref=chooser-v1" alt="BY-"><img style="height:15px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/nc.svg?ref=chooser-v1" alt="NC-"><img style="height:15px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/nd.svg?ref=chooser-v1" alt="ND 4.0"></a>'

license-img-lrg: '<a href="http://creativecommons.org/licenses/by-nc-nd/4.0/?ref=chooser-v1" target="_blank" rel="license noopener noreferrer" style="display:inline-block;"><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/cc.svg?ref=chooser-v1" alt="CC "><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/by.svg?ref=chooser-v1" alt="BY-"><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/nc.svg?ref=chooser-v1" alt="NC-"><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/nd.svg?ref=chooser-v1" alt="ND 4.0"></a>'

license-summary: 'You may redistribute (but not remix or copy) content on this site under the same license as above for non-commercial purposes provided that you provide attribution and link back to the source.'

theme-license: '<a href="https://github.com/clayh53/tufte-jekyll">Tufte-Jekyll theme</a> is &copy; <a href="http://www.clayharmon.com/">Clay Harmon</a> and distributed under the MIT license. This site theme is also distributed under the MIT license.'

credits: 'This page was generated by <a href="https://pages.github.com">GitHub Pages</a> using a heavily modified version of the <a href="https://github.com/clayh53/tufte-jekyll">Tufte-Jekyll theme</a> by <a href="http://www.clayharmon.com/">Clay Harmon</a>.'

markdown: redcarpet
redcarpet:
    extensions: ["no_intra_emphasis", "tables", "autolink", "strikethrough", "with_toc_data"]

markdown_ext: "markdown,mkdown,mkdn,mkd,md"
permalink: pretty
timezone: America/New_York
excerpt_separator: <!--more-->  # you can specify your own separator, of course.
exclude: ['.gitignore', 'Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md', 'deploy.sh', 'deploy-onion.sh']
post:
  template: _post.txt
  extension: md
page:
  template: _page.txt
  extension: md
editor: gvim
git:
  branch: master
transfer:
  command: rsync
  settings: -av
  source: _site/
  destination: ~/workspace/jdmar3.github.io
